repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: debug-statements
        language_version: python3

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        args: [--safe, --quiet]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args: [--docstring-convention, pep257]
        language_version: python3
        additional_dependencies:
          - flake8-typing-imports==1.9.0
          - flake8-docstrings==1.5.0
          - flake8-rst-docstrings==0.0.14

#-   repo: local
#    hooks:
#    -   id: flake8
#        name: flake8
#        entry: flake8
#        files: ^.*.py$
#        language: python
#        language_version: python3
#        additional_dependencies:
#          - flake8-typing-imports==1.9.0
#          - flake8-docstrings==1.5.0
