from http import HTTPStatus
import requests
from pathlib import Path
from json import dumps


# More info on the data this module is based on is available here:
# https://www.census.gov/geographies/reference-files/2010/geo/county-adjacency.html
US_DATA_URL = "https://www2.census.gov/geo/docs/reference/county_adjacency.txt"

DATA_FILE_ENCODING = "ISO8859-1"

TEMPLATE = """
# flake8: noqa

# Note: This file is automatically generated.  Structure is subject to change.

united_states_adjacency_data = {adjacency_data}

"""

data = {}

response = requests.get(US_DATA_URL)

if not response.status_code == HTTPStatus.OK:
    print(f"Error getting adjacency data - url: {US_DATA_URL} status: {response.status_code}")
    exit(1)

contents = response.content.decode(response.encoding).splitlines()

current_mark = ""
for i, line in enumerate(contents):

    tab_delimited = [_.strip('"') for _ in contents[i].split("\t")]

    if not len(tab_delimited) == 4:
        continue

    mark_county, mark_county_fips, adjacent_county, adjacent_county_fips = tab_delimited

    if not mark_county == "":
        current_mark = mark_county
        data[current_mark] = dict(fips=mark_county_fips, adjacent=[])
        continue

    if current_mark == adjacent_county:
        continue

    data[current_mark]["adjacent"].append(adjacent_county)

with open(
    Path(__file__).parent.parent / "src" / "county_adjacency" / "data2.py",
    "w",
) as f:
    f.write(TEMPLATE.format(adjacency_data=dumps(data, indent=4)))
